version: '3.9'
services:
  db:
    image: postgres:15
    container_name: nyaysetu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nyay
      POSTGRES_PASSWORD: nyay
      POSTGRES_DB: nyay
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nyaysetu-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
